-- AlterTable
ALTER TABLE "lists" ALTER COLUMN "created_date" SET DEFAULT CURRENT_DATE,
ALTER COLUMN "created_date" SET DATA TYPE DATE,
ALTER COLUMN "modified_date" SET DEFAULT CURRENT_DATE,
ALTER COLUMN "modified_date" SET DATA TYPE DATE;
